# Fichier de configuration générique (à adapter au projet)
dataset:
  name: CUB-200-2011        # ex: "CIFAR10", "IMDB", ...
  root: "./data"            # chemin local pour les données
  split:                    # optionnel : noms/tailles de splits
    train: "train"
    val: "val"
    test: "test"
  download: true            # si supporté
  num_workers: 1          # réduit pour éviter OOM GPU
  shuffle: true

preprocess:
  # transformations de base (ex: resize, normalize)
  resize: [224, 224]                  # ex: [32, 32] ou null
  normalize: 
    mean: [0.48185426, 0.50031734, 0.42832923]
    std: [0.2270571, 0.2226704, 0.26213554]           # ex: {"mean": [0.5,0.5,0.5], "std":[0.5,0.5,0.5]} ou null
  text_tokenizer:   null        # pour NLP : nom ou paramètres, sinon null

augment:
  # data augmentation (laisser null si non utilisée)
  random_flip: true             # true/false
  random_rotation: false        # true/false
  color_jitter:
    brightness: 0.05
    contrast: 0.05
    saturation: 0.0
    hue: 0.0     
  spec_augment: null            # pour audio : paramètres ou null

model:
  type: cnn               # ex: "resnet18", "mlp", "lstm", ...
  num_classes: 200
  input_shape: [3, 224, 224] # ex: [3, 32, 32] ou null
  hidden_sizes: [64, 128, 256]            # ex: [256, 128] ou null
  activation: relu          # ex: relu, gelu, tanh...
  dropout: 0.0              # ex: 0.0–0.5
  batch_norm: true         # true/false
  residual: false           # true/false
  attention: false          # true/false
  rnn:                      # pour RNN/LSTM/GRU : paramètres ou null
    type: null              # lstm/gru
    hidden_size: null
    num_layers: null
    bidirectional: false
  groups: 4
  num_blocks : 2          

train:
  seed: 42
  device: auto              # "cpu", "cuda", ou "auto"
  batch_size: 32
  epochs: 20
  max_steps: null           # entier ou null
  overfit_small: false      # true pour sur-apprendre sur un petit échantillon

  optimizer:
    name: adam              # sgd/adam/rmsprop
    lr: 0.0005
    weight_decay: 0.0       # régularisation L2
    momentum: 0.9           # utile si SGD

  scheduler:
    name: none              # none/step/cosine/onecycle
    step_size: 10
    gamma: 0.1
    warmup_steps: 0

metrics:
  classification:           # ex: ["accuracy", "f1"]
    - accuracy
  regression: []            # ex: ["mae", "rmse"]

hparams:                    # espace pour mini grid search
  lr: [0.0005, 0.001, 0.002]
  weight_decay: [0.0, 0.0001]
  num_blocks : [2, 3]
  groups: [2, 4]

paths:
  runs_dir: "./runs"
  artifacts_dir: "./artifacts"